name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      prerelease:
        description: 'Prerelease'
        required: true
        default: false
        type: boolean
      skip-if-no-diff:
        description: 'Skip if no diff'
        required: true
        default: false
        type: boolean
      diff-targets:
        description: 'Diff Targets'
        required: false
        default: '{README.md,LICENSE,dist/**/*}'
        type: string
      dry-run:
        description: 'Dry run'
        required: true
        default: false
        type: boolean

jobs:
  # eslint:
  #   uses: ./.github/workflows/eslint.yaml

  codeql:
    uses: ./.github/workflows/codeql.yaml
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

  release:
    name: Release
    needs: [codeql]
    concurrency: release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag }}
      skipped: ${{ steps.release.outputs.skipped }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Pnpm Install
        uses: uxiew/action-setup-node-pnpm@v1

      - id: release
        uses: CatChen/node-package-release-action@v1
        with:
          release-type: ${{ inputs.release-type || 'patch' }}
          prerelease: ${{ inputs.prerelease || false }}
          update-shorthand-release: true
          dry-run: ${{ inputs.dry-run || false }}
          skip-if-no-diff: ${{ inputs.skip-if-no-diff || github.event_name != 'workflow_dispatch' }}
          diff-targets: ${{ inputs.diff-targets || '{README.md,LICENSE,dist/**/*}' }}
          github-token: ${{secrets.GITHUB_TOKEN}}

  publish:
    name: Publish
    needs: [release]
    if: ${{ needs.release.outputs.skipped != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ needs.release.outputs.tag }}

      - uses: actions/checkout@v4
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}

      - name: Node & Pnpm Install
        uses: uxiew/action-setup-node-pnpm@v1
        with:
          args: '--frozen-lockfile'

      - name: Build & Test
        run: |
          pnpm test

      - name: Publish 🚀
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          NPM_WHOAMI=$(npm whoami)
          echo "::notice::NPM username: $NPM_WHOAMI"

          echo "::group::npm config"
          npm config ls -l
          echo "::endgroup::"

          echo "::group::npm config"
          if [[ "$DRY_RUN" = true ]]
          then
            pnpm publish --dry-run
          else
            pnpm publish --access=public --no-git-checks
          fi
          echo "::endgroup::"
